### PR TITLE
adding licence and updating readme

### PR DESCRIPTION
**Pull request by dan-mi-sun**
Updating with licence. This may change with time, but better to put in there early. May want to consider having an Authors file at some point such as here: https://github.com/dyne/Tomb/blob/master/AUTHORS.md

Reason being is that alot of the people who are going to be contributing the juice to the soul of the platform aren't going to be making commits in git or within the code. Always good to attribute where possible ;)

### CODE REVIEW

**Comment by dan-mi-sun** [comment]
Just seen the conflict. Will fix this up tomorrow *yawns*.

**Comment by KGibb8** [comment]
First conflict! Whoop whoop!

**Comment by dan-mi-sun** [comment]
Was always gonna be me ;)

**Comment by dan-mi-sun** [comment]
Am going to redo and resubmit this as a lot has changed since...

**Pull request closed without merging**
