### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by dan-mi-sun**
Updating README with content from Loomio MMT description proposal:

https://www.loomio.org/d/YfwNlc0W/formulating-a-description-of-the-project

### CODE REVIEW

**Comment by dan-mi-sun** [comment]
Just had to fix up a pretty nasty rebase with `development`. Any comments on this one please take over to here:

https://www.loomio.org/d/YfwNlc0W/formulating-a-description-of-the-project%3Ffrom=34

**Comment by dan-mi-sun** [comment]
@blockades/mmt Ok, this has passed the loomio vote. Ready to merge.

**Comment by ameba23** [comment]
Looks grand.  Will be great to have this page up to finally show friends what this is about

**Comment by ameba23** [comment]
but not sure how to approve it or who can approve it

**Comment by dan-mi-sun** [comment]
We still need to figure out the formalities of who has what permissions. 

At the moment here are the people in the team: https://github.com/orgs/blockades/teams/mmt/members

@KGibb8 @nikolai-b and myself are 'admins' so have the ability to merge code.

@ameba23 do you see a button which says review code? Or Agree? Or something like that?

**Comment by KGibb8** [comment]
@ameba23 you should be able to review code if you go to the 'files changed' tab and top right there's a 'review changes' button.

**Pull request merged**
