### PR TITLE
One approach!

### PR DESCRIPTION
**Pull request by KGibb8**

### CODE REVIEW

**Comment by nikolai-b** [comment]
Code looks fine, does it work? :smile:

**Comment by KGibb8** [comment]
Its actually exposed an issue in the transaction system... I'm creating an issue now

**Comment by KGibb8** [comment]
See: https://github.com/blockades/mmt/issues/44

**Comment by KGibb8** [comment]
Tests failing due to this issue: https://github.com/blockades/mmt/issues/51

**Comment by KGibb8** [comment]
Another issue... https://github.com/blockades/mmt/issues/50

**Pull request merged**
